name: Build Plugin and Upload Artifact

on:
  release:
    types:
      - created # This runs when a new release is manually created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust the Node.js version as needed
          cache: 'npm'

      - name: Install Node.js dependencies
        run: npm install

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Adjust PHP version based on your project

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist

      - name: Build Plugin
        run: npm run build-plugin

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload agentwp.zip as a release asset
        uses: softprops/action-gh-release@v1
        with:
          files: agentwp.zip
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
