name: 🐥 Release the Plugin to Private Repo

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Build plugin
        run: npm run build-plugin

      - name: rsync plugin to production
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          path: agentwp.zip
          remote_path: /home/forge/plugin.agentwp.com/packages/
          remote_host: '159.89.86.196'
          remote_user: 'forge'
          remote_key: ${{ secrets.GH_RSA_SECRET }}
