name: Deploy to WordPress.org
on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Build
        run: |
          npm install
          npm run build
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
